services:
  inventory:
    image: ghcr.io/bketelsen/inventory:0.7.3
    ports:
      - 9999:9999
      - 8000:8000
    restart: always
    command: ["server"]
    volumes:
      - type: bind
        source: ./inventory.yaml
        target: /etc/inventory/inventory.yaml
        read_only: true
